name: Validate JSON Files

on:
  pull_request:
    paths:
      - "public/videos/**.json"
      - "public/songs.json"
      - "public/artists.json"
      - "schema/**.json"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate JSON files
        run: node scripts/validateJsonSchemas.js
